name: GitHub Pages Deploy

on:
  push:
    branches:
      - main # Cambia "main" por la rama en la que deseas hacer el deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Cambia a la versión de Node.js que estés utilizando en tu proyecto

      - name: Install dependencies
        run: npm install

      - name: Build Next.js project
        run: npm run build

      - name: Configure Git identity
        run: |
          git config --global user.email "krhistian1902@gmail.com"
          git config --global user.name "CristiAndLook"

      - name: Deploy to GitHub Pages
        env:
          NEXT_PUBLIC_BASE_PATH: '/ganesha-samples-app-nextjs' # Cambia "/ganesha-samples-app-nextjs" por la ruta base de tu proyecto
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          npm install -g gh-pages
          gh-pages -d out -b gh-pages -t

